development:
  adapter: postgresql
  encoding: unicode
  database: sleep_underflow_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: sleep_underflow_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: sleep_underflow_production
  pool: 5
  timeout: 5000

